const LOGO = id => "https://a.espncdn.com/i/teamlogos/ncaa/500/"+id+".png";
const GAMES = {
"tamu-asu":{title:"No. 10 Texas A&M vs Arizona State",away:9,home:245,awayN:"Arizona State",homeN:"Texas A&M",meta:"Saturday, Sept. 12, 2026 | 12:00 p.m. ET | Kyle Field | ABC",spread:"Current: TAMU -14.5 / ASU +14.5",openS:"Open: TAMU -13.5",total:"Current: 50.5",openT:"Open: 52.5",ml:"TAMU -704 / ASU +509",move:"Aggies out to -14.5. Total down 2.",staffA:"Kenny Dillingham said this is as big a step up as ASU gets. Sun Devils 1-0.",staffB:"Mike Elko at Kyle Field. Home double-digit favorite after a cupcake.",meansA:"ASU has to steal early downs. +14.5 is the live number if A&M is sloppy.",meansB:"-14.5 is a lot in Week 2. We need the ones to play 60 minutes to fire it.",scriptA:"ASU WIN IF -- ASU 24 | TAMU 31. Keep it one score into the fourth.",scriptB:"TAMU WIN IF -- TAMU 35 | ASU 17. Front seven ends ASU drives before the plus-40.",wr:"ASU WR1 vs TAMU CB1 -- if the Aggies sit two-high the Sun Devil slot has to work.",bet:"Texas A&M -13.5 (-110)",conf:"LEAN",note:"Posted TAMU -13.5. Market is now -14.5. Still a LEAN, not a fire."},
"ore-okst":{title:"No. 6 Oregon at Oklahoma State",away:248,home:197,awayN:"Oregon",homeN:"Oklahoma State",meta:"Saturday, Sept. 12, 2026 | 12:00 p.m. ET | Boone Pickens | ESPN",spread:"Current: ORE -23.5 / OKST +23.5",openS:"Open: ORE -20.5",total:"Current: 54.5",openT:"Open: 55.5",ml:"ORE heavy",move:"Oregon out to -23.5 after opening -20.5.",staffA:"Dan Lanning. Ducks 34-27 over Boise. That was not a statement win.",staffB:"Oklahoma State 0-1 at home against a top-10 offense.",meansA:"A 20-point road favorite that just survived Boise is the hangover number.",meansB:"+23.5 is the number if Oregon's ones sit after the half.",scriptA:"ORE WIN IF -- ORE 38 | OKST 17. Tempo from the first series.",scriptB:"OKST WIN IF -- OKST 24 | ORE 31. Steal a red-zone trip and keep the ones on the sideline late.",wr:"Oregon WR1 vs OKST CB1. If the Cowboys cannot travel with speed, this is 30-plus.",bet:"Oregon -20.5 (-110)",conf:"LEAN",note:"Ticket is ORE -20.5. Market drifted to -23.5. LEAN only."},
"uga-wku":{title:"No. 2 Georgia vs Western Kentucky",away:98,home:61,awayN:"Western Kentucky",homeN:"Georgia",meta:"Saturday, Sept. 12, 2026 | 12:45 p.m. ET | Sanford Stadium | SECN",spread:"Current: UGA -39.5 / WKU +39.5",openS:"Open: UGA -35.5",total:"Current: 55.5",openT:"Open: 58.5",ml:"UGA heavy",move:"Georgia out to -39.5.",staffA:"WKU 0-1. This is whether they keep a half close.",staffB:"Kirby Smart. Georgia 63-3 in the opener. Maintenance.",meansA:"+39.5 is not a live fire. Bench bet.",meansB:"Ones play a half or they do not. FADE the number either way.",scriptA:"WKU WIN IF -- does not apply as a side. Stay within 28 at half.",scriptB:"UGA WIN IF -- UGA 45 | WKU 7. Ones through one half.",wr:"Georgia WR1 vs WKU CB1. Mismatch if the ones stay out.",bet:"Georgia -35.5",conf:"FADE",note:"Posted because every Top-25 game needs a number. Would not fire 35-plus."},
"nd-rice":{title:"No. 3 Notre Dame vs Rice",away:242,home:87,awayN:"Rice",homeN:"Notre Dame",meta:"Saturday, Sept. 12, 2026 | 3:30 p.m. ET | Notre Dame Stadium | NBC",spread:"Current: ND -28.5 / RICE +28.5",openS:"Open: ND -28.5",total:"Current: 51.5",openT:"Open: 51.5",ml:"ND heavy",move:"Held -28.5.",staffA:"Rice visitor on NBC. Paycheck.",staffB:"Freeman home maintenance before the real slate.",meansA:"Do not fire +28.5 hoping Rice keeps a half.",meansB:"FADE the number even if ND covers.",scriptA:"RICE WIN IF -- not the script. Stay inside 21 at half.",scriptB:"ND WIN IF -- ND 38 | RICE 7.",wr:"ND WR1 vs Rice CB1. Mismatch.",bet:"Notre Dame -28.5",conf:"FADE",note:"28-plus is a bench bet. Posted for the card only."},
"iu-how":{title:"No. 5 Indiana vs Howard",away:47,home:84,awayN:"Howard",homeN:"Indiana",meta:"Saturday, Sept. 12, 2026 | 12:00 p.m. ET | Memorial Stadium | BTN",spread:"Current: IU -45.5 / HOW +45.5",openS:"Open: IU -45.5",total:"Current: 62.5",openT:"Open: 62.5",ml:"IU heavy",move:"Held.",staffA:"Howard FCS.",staffB:"Indiana defending champ. Same FCS-cover problem as Virginia Friday.",meansA:"Do not live on Howard +45.",meansB:"Virginia cashed 45.5. That does not make this a BET.",scriptA:"HOW WIN IF -- not the side.",scriptB:"IU WIN IF -- IU 56 | HOW 3.",wr:"Indiana WR1 vs Howard CB. Mismatch.",bet:"Indiana -45.5",conf:"FADE",note:"FCS landmine. Posted only so the card is full."},
"byu-ariz":{title:"No. 15 BYU vs Arizona",away:12,home:252,awayN:"Arizona",homeN:"BYU",meta:"Saturday, Sept. 12, 2026 | 3:30 p.m. ET | LaVell Edwards | FOX",spread:"Current: BYU -6.5 / ARIZ +6.5",openS:"Open: BYU -6.5",total:"Current: 50.5",openT:"Open: 50.5",ml:"BYU -250 / ARIZ +205",move:"Held -6.5 / 50.5.",staffA:"Arizona 1-0. First real road test.",staffB:"Kalani Sitake at home. 6.5 is a real number.",meansA:"+6.5 is live if BYU starts slow.",meansB:"Home favorite a touchdown is the LEAN pile with Utah-Arkansas.",scriptA:"ARIZ WIN IF -- ARIZ 24 | BYU 23. Steal a red-zone trip.",scriptB:"BYU WIN IF -- BYU 27 | ARIZ 17. Front seven ends Arizona early downs.",wr:"Arizona WR1 vs BYU CB1. If BYU sits two-high the slot has to work.",bet:"BYU -6.5 (-110)",conf:"LEAN",note:"Actual game. 6.5 home favorite is the ticket we posted."},
"ttu-orst":{title:"No. 13 Texas Tech at Oregon State",away:2641,home:204,awayN:"Texas Tech",homeN:"Oregon State",meta:"Saturday, Sept. 12, 2026 | 7:30 p.m. ET | Reser Stadium | CBS",spread:"Current: TTU -17.5 / ORST +17.5",openS:"Open: TTU -17.5",total:"Current: 54.5",openT:"Open: 54.5",ml:"TTU heavy",move:"Held a two-score road number.",staffA:"Joey McGuire. Tech should win. 17.5 on the road is the tax.",staffB:"Beavers 0-1 at home.",meansA:"Do not need -17.5 to like Tech. LEAN the side we posted.",meansB:"+17.5 is the dog if Tech's ones sit after 28-7.",scriptA:"TTU WIN IF -- TTU 38 | ORST 17.",scriptB:"ORST WIN IF -- ORST 24 | TTU 31.",wr:"Tech WR1 vs ORST CB1. Speed mismatch if it stays on schedule.",bet:"Texas Tech -17.5 (-110)",conf:"LEAN",note:"Road two-score favorite. LEAN, not a fire."},
"psu-tem":{title:"No. 16 Penn State at Temple",away:213,home:218,awayN:"Penn State",homeN:"Temple",meta:"Saturday, Sept. 12, 2026 | 12:00 p.m. ET | Lincoln Financial | ESPN2",spread:"Current: PSU -24.5 / TEM +24.5",openS:"Open: PSU -24.5",total:"Current: 52.5",openT:"Open: 52.5",ml:"PSU heavy",move:"Held.",staffA:"James Franklin on the road in Philly. Maintenance.",staffB:"Temple home. Need a half to keep +24.5 interesting.",meansA:"24.5 is FADE size even if PSU covers.",meansB:"Do not fire the Owl plus.",scriptA:"PSU WIN IF -- PSU 38 | TEM 10.",scriptB:"TEM WIN IF -- stay inside 17 at half.",wr:"Penn State WR1 vs Temple CB. Mismatch if the ones play.",bet:"Penn State -24.5",conf:"FADE",note:"Bench number. Posted for the card."},
"wash-usu":{title:"No. 19 Washington vs Utah State",away:328,home:264,awayN:"Utah State",homeN:"Washington",meta:"Saturday, Sept. 12, 2026 | 3:30 p.m. ET | Husky Stadium | BTN",spread:"Current: WASH -28.5 / USU +28.5",openS:"Open: WASH -28.5",total:"Current: 56.5",openT:"Open: 56.5",ml:"WASH heavy",move:"Held.",staffA:"Utah State visitor.",staffB:"Huskies get-right at home.",meansA:"+28.5 is not live.",meansB:"FADE 28-plus.",scriptA:"USU WIN IF -- not the side.",scriptB:"WASH WIN IF -- WASH 42 | USU 10.",wr:"Washington WR1 vs USU CB. Mismatch.",bet:"Washington -28.5",conf:"FADE",note:"28-point home favorite. Bench."},
"utah-ark":{title:"No. 20 Utah vs Arkansas",away:8,home:254,awayN:"Arkansas",homeN:"Utah",meta:"Saturday, Sept. 12, 2026 | 10:15 p.m. ET | Rice-Eccles | ESPN",spread:"Current: UTAH -7 / ARK +7",openS:"Open: UTAH -7",total:"Current: 54.5",openT:"Open: 54.5",ml:"UTAH -280 / ARK +230",move:"Held a touchdown.",staffA:"Arkansas 1-0 on the road at night.",staffB:"Whittingham at home. 7 is a real number.",meansA:"+7 is live if Utah starts slow in a night opener.",meansB:"Home favorite a touchdown sits with BYU -6.5 on the LEAN pile.",scriptA:"ARK WIN IF -- ARK 27 | UTAH 24.",scriptB:"UTAH WIN IF -- UTAH 31 | ARK 17.",wr:"Arkansas WR1 vs Utah CB1. Night game, two-high likely on third down.",bet:"Utah -7 (-110)",conf:"LEAN",note:"Actual game. Home 7 is the ticket."},
"usc-ull":{title:"No. 14 USC vs Louisiana",away:309,home:30,awayN:"Louisiana",homeN:"USC",meta:"Saturday, Sept. 12, 2026 | 11:00 p.m. ET | LA Memorial Coliseum | ESPN",spread:"Current: USC -21.5 / ULL +21.5",openS:"Open: USC -21.5",total:"Current: 58.5",openT:"Open: 58.5",ml:"USC heavy",move:"Held.",staffA:"Louisiana visitor late window.",staffB:"Lincoln Riley. Trojans already 2-0. Maintenance.",meansA:"+21.5 only if USC sits ones after 28-0.",meansB:"FADE 21-plus home favorites in a late window.",scriptA:"ULL WIN IF -- stay inside 14 at half.",scriptB:"USC WIN IF -- USC 42 | ULL 14.",wr:"USC WR1 vs Louisiana CB. Mismatch.",bet:"USC -21.5",conf:"FADE",note:"Late-window maintenance. Bench."},
"lsu-lt":{title:"No. 8 LSU vs Louisiana Tech",away:234,home:99,awayN:"Louisiana Tech",homeN:"LSU",meta:"Saturday, Sept. 12, 2026 | 7:30 p.m. ET | Tiger Stadium | SECN+",spread:"Current: LSU -34.5 / LT +34.5",openS:"Open: LSU -34.5",total:"Current: 57.5",openT:"Open: 57.5",ml:"LSU heavy",move:"Held after 51-10 over Clemson.",staffA:"Louisiana Tech visitor.",staffB:"Kiffin after a statement opener. Ones through a half.",meansA:"Do not fire +34.5.",meansB:"FADE 34-plus even after Clemson.",scriptA:"LT WIN IF -- not the side.",scriptB:"LSU WIN IF -- LSU 45 | LT 7.",wr:"LSU WR1 vs LT CB. Mismatch.",bet:"LSU -34.5",conf:"FADE",note:"Get-right number. Not a fire."},
"miss-char":{title:"No. 9 Ole Miss vs Charlotte",away:2429,home:145,awayN:"Charlotte",homeN:"Ole Miss",meta:"Saturday, Sept. 12, 2026 | 7:45 p.m. ET | Vaught-Hemingway | ESPN",spread:"Current: MISS -31.5 / CHAR +31.5",openS:"Open: MISS -31.5",total:"Current: 60.5",openT:"Open: 60.5",ml:"MISS heavy",move:"Held after 41-38 over Louisville.",staffA:"Charlotte visitor.",staffB:"Rebels just survived Louisville. This should be a half.",meansA:"+31.5 is not live.",meansB:"FADE 31-plus after a one-score opener.",scriptA:"CHAR WIN IF -- not the side.",scriptB:"MISS WIN IF -- MISS 42 | CHAR 10.",wr:"Ole Miss WR1 vs Charlotte CB. Mismatch.",bet:"Ole Miss -31.5",conf:"FADE",note:"Hangover maintenance. Bench."},
"smu-ucd":{title:"No. 17 SMU vs UC Davis",away:302,home:2567,awayN:"UC Davis",homeN:"SMU",meta:"Saturday, Sept. 12, 2026 | 4:00 p.m. ET | Ford Stadium | ACCNX",spread:"Current: SMU -28.5 / UCD +28.5",openS:"Open: SMU -28.5",total:"Current: 58.5",openT:"Open: 58.5",ml:"SMU heavy",move:"Held.",staffA:"UC Davis FCS/G5 style visitor.",staffB:"SMU home maintenance.",meansA:"Do not fire the plus.",meansB:"FADE 28-plus.",scriptA:"UCD WIN IF -- not the side.",scriptB:"SMU WIN IF -- SMU 42 | UCD 10.",wr:"SMU WR1 vs UCD CB. Mismatch.",bet:"SMU -28.5",conf:"FADE",note:"Bench number."},
"hou-sou":{title:"No. 22 Houston vs Southern",away:2582,home:248,awayN:"Southern",homeN:"Houston",meta:"Saturday, Sept. 12, 2026 | 7:00 p.m. ET | TDECU | ESPN+",spread:"Current: HOU -35.5 / SOU +35.5",openS:"Open: HOU -35.5",total:"Current: 59.5",openT:"Open: 59.5",ml:"HOU heavy",move:"Held.",staffA:"Southern FCS.",staffB:"Houston paycheck.",meansA:"Not a live plus.",meansB:"FADE 35-plus.",scriptA:"SOU WIN IF -- not the side.",scriptB:"HOU WIN IF -- HOU 49 | SOU 7.",wr:"Houston WR1 vs Southern CB. Mismatch.",bet:"Houston -35.5",conf:"FADE",note:"FCS paycheck. Bench."}
};
function paint(g, review){
  if (!g) { document.body.innerHTML = "<p style='color:#fff;padding:40px'>Board not found. <a href='cfb.html'>CFB</a></p>"; return; }
  document.title = "The Split -- "+g.title;
  const stamp = "LAST UPDATED: Sat Sep 12, 2026 8:56 a.m. ET";
  const res = review ? `<details class="block" open><summary>REVIEW</summary><div class="body"><div class="callout"><div style="font-size:22px;font-weight:800">${g.bet||""}</div><div class="${g.result==="WIN"?"ok":"push"}">${g.result||"OPEN"} -- ${g.final||""}</div></div></div></details>` : `<details class="block" open><summary>BEST BET</summary><div class="body"><div class="callout"><div style="font-size:22px;font-weight:800">${g.bet||""}</div><div>${g.conf||"LEAN"}</div></div><ul><li>${g.note||""}</li></ul></div></details>`;
  document.getElementById("app").innerHTML = `
  <div class="topnav"><a href="today.html">TODAY</a><a href="cfb.html">CFB</a><a href="reviews.html">BET TRACKER</a></div>
  <header><div class="brand">THE SPLIT</div><div class="week">COLLEGE FOOTBALL WEEK 2</div>
  <div class="logos"><img src="${LOGO(g.away)}" alt=""/><img src="${LOGO(g.home)}" alt=""/></div>
  <h1>${g.title.toUpperCase()}</h1><div class="meta">${g.meta||""}</div>
  <div class="updated">${stamp}</div></header>
  <div class="wrap">
    <div class="market">
      <div class="tile"><b>SPREAD</b><span>${g.spread||"--"}</span><span>${g.openS||""}</span></div>
      <div class="tile"><b>TOTAL</b><span>${g.total||"--"}</span><span>${g.openT||""}</span></div>
      <div class="tile"><b>MONEYLINE</b><span>${g.ml||"--"}</span></div>
      <div class="tile"><b>MOVE</b><span>${g.move||"--"}</span></div>
    </div>
    <details class="block"><summary>TEAM BREAKDOWN</summary><div class="body grid2">
      <div><div class="team-head"><img src="${LOGO(g.away)}" alt=""/><b>${g.awayN}</b></div><h3>STAFF / STATUS</h3><p>${g.staffA||""}</p><h3>WHAT THAT MEANS</h3><p>${g.meansA||""}</p></div>
      <div><div class="team-head"><img src="${LOGO(g.home)}" alt=""/><b>${g.homeN}</b></div><h3>STAFF / STATUS</h3><p>${g.staffB||""}</p><h3>WHAT THAT MEANS</h3><p>${g.meansB||""}</p></div>
    </div></details>
    <details class="block"><summary>INACTIVES</summary><div class="body"><p class="note">College does not post an NFL-style sheet. No confirmed sit-outs locked for this game as of Saturday morning.</p></div></details>
    <details class="block"><summary>SCRIPT</summary><div class="body"><p>${g.scriptA||""}</p><p>${g.scriptB||""}</p></div></details>
    <details class="block"><summary>WR VS CB</summary><div class="body"><p>${g.wr||""}</p></div></details>
    ${res}
    <p class="note">No DFS on college boards. Review posts after the final.</p>
  </div>`;
}
