window.NFL_OFF = {
ne:{offscheme:"McDaniels 11 personnel. Tempo after chunks. TE is the pressure valve.",engine2:"Raridon scored the first TD of 2026. Stevenson was the featured back with Henderson out. Henry was the checkdown. Maye still moved it between the three interceptions.",offhole:"Turnovers killed drives. Three interceptions. 10 points.",howoff:"Skip Maye as captain. TE or the back if you need a Patriot.",broke:"The pass script. Pocket and ball security. The tight end and the back still touched it."},
sea:{offscheme:"Fleury play-action. 12 personnel to settle a rookie back.",engine2:"JSN 8-122-1. Lock threw the 45-yard tying score. Price was the first-round lead back.",offhole:"Could not finish drives. Three takeaways on defense produced only 13 points.",howoff:"JSN only.",broke:"Red zone and finish. JSN moved it. The rest of the room did not."},
sf:{offscheme:"Shanahan outside zone. 21 and 12 personnel.",engine2:"Purdy 205. CMC 68 rush, 20 receiving. Control script, not explosives.",offhole:"CMC piled yards and did not score.",howoff:"Do not auto-captain CMC.",broke:"The back did not finish. The side still cashed."},
lar:{offscheme:"McVay 11 personnel.",engine2:"Nacua 74. Stafford never found a closer. Adams was quiet after the flight.",offhole:"Script gone after the first half. 7 points.",howoff:"Do not stack the home QB on a short week.",broke:"Travel plus a road dog that can run. Explosives died."},
chi:{offscheme:"Dual-threat QB. Two-back zone. Play-action off the run.",engine2:"Swift 18-124-3. Monangai 100-1. Williams two pass TDs and two rush TDs. 291 rush yards.",offhole:"Did not break on offense.",howoff:"Swift is the slate.",broke:"Did not break. 59 points. The other sideline broke."},
car:{offscheme:"Young dropback volume. Idzik first-year call.",engine2:"Young 361-3. Coker 8-138. 37 points.",offhole:"Offense scored enough. The run defense lost the game.",howoff:"Coker is live. Carolina points are not.",broke:"Not on offense. 291 rush yards the other way."},
tb:{offscheme:"Robinson call. Mayfield dropback.",engine2:"Irving found the end zone. Mayfield still moved it between four giveaways. 27 points.",offhole:"Ball security. Four giveaways lost the number.",howoff:"Irving without the Bucs side.",broke:"Turnovers. The back still scored."},
cin:{offscheme:"Burrow. 11 personnel. Chase was not required this week.",engine2:"Burrow 254. Gesicki 78. Chase Brown 56. Defense scored.",offhole:"Chase was quiet. The front covered for him.",howoff:"Do not force the Chase stack.",broke:"WR1 volume. Not the side."},
no:{offscheme:"Moore / Nussmeier dropback volume.",engine2:"Shough 410. Olave 182. 30 points.",offhole:"Did not break. Lost in OT because Gibbs ran through the light box.",howoff:"Olave is the Saint.",broke:"Not on offense. Light-box defense was the problem."},
det:{offscheme:"Featured-back offense. Gibbs is the call.",engine2:"Gibbs 29-156-2. St. Brown scored.",offhole:"Needed overtime. Did not cover 7.5.",howoff:"Gibbs is the Lion. The number leaked.",broke:"Enough to win. Not enough to cover a touchdown-plus home number."},
buf:{offscheme:"Allen play-action. Designed quarterback run. Tight end volume.",engine2:"Allen 334 and two rush TDs. Kincaid 130 yards. DJ Moore 100.",offhole:"Kincaid yards without the score.",howoff:"Allen is the side. Kincaid is not a captain.",broke:"The tight end did not finish. The closer did."},
hou:{offscheme:"Stroud dropback. Featured back in the red zone.",engine2:"Montgomery three TDs. Stroud moved it until the last drive.",offhole:"Strip sack after they got back into the red zone. Hung 31 and lost.",howoff:"Montgomery without Houston points.",broke:"The last drive. Not the first three quarters."},
bal:{offscheme:"Run first. Play-action off Henry.",engine2:"Henry 24-144-3. Lamar 324. Flowers 150. 506 yards.",offhole:"Did not break.",howoff:"Henry first. Then Lamar.",broke:"Did not break."},
ind:{offscheme:"Taylor downhill. Jones after Achilles, reduced scramble.",engine2:"Taylor 98-2. Jones 149 pass yards.",offhole:"Pass game vs Minter. Fell in a 28-6 hole.",howoff:"Taylor anytime. Not Colts points.",broke:"The dropback game. Taylor still moved it on the ground."},
cle:{offscheme:"Watson dropback. Protection did not hold.",engine2:"Watson 205. That was the entire tree. Five sacks taken.",offhole:"Third down 1-of-8. Protection. 10 points.",howoff:"Do not board this offense.",broke:"The line and third down. They still completed passes. They could not stay on the field."},
jax:{offscheme:"Lawrence vs a dead road offense.",engine2:"Lawrence 245, four TD passes. Tuten 66 rush.",offhole:"Did not break. Opponent was Cleveland.",howoff:"Home vs a dead offense: lay it.",broke:"Did not break. Caution is opponent quality."},
atl:{offscheme:"Bijan is the call. Everyone else is window dressing.",engine2:"Bijan 83 rush, 90 receiving, 1 TD. That was the offense.",offhole:"Drive-to-drive scoring died around him. 13 points.",howoff:"Bijan without the Falcons side.",broke:"Everyone except Bijan."},
pit:{offscheme:"Limited dropback. Watt scored the splash.",engine2:"Rodgers 221 and a score. The rest was field position.",offhole:"Never a stack. Front won it.",howoff:"Do not pay the Steelers pass game in a 20-13.",broke:"Explosives. They did not need them."},
nyj:{offscheme:"Hall and the clock. Possession, not explosives.",engine2:"Hall 22-102-1. Geno 215. Wilson 79. 38:46 time of possession.",offhole:"Not explosive. Did not need to be.",howoff:"Hall is the Jet.",broke:"Did not break."},
ten:{offscheme:"Daboll first year. Ward dropback.",engine2:"Ward 140. That was the tree. Three sacks taken.",offhole:"Protection. Home opener script. 195 yards.",howoff:"Do not stack this home opener.",broke:"The line. Ward still completed balls. Hall ran the clock the other way."},
ari:{offscheme:"Brissett. McBride the security blanket.",engine2:"Brissett 277. McBride 95. 394 yards. Harrison 0 TD.",offhole:"Harrison did not finish. The rest of the offense did.",howoff:"Harrison TD is not required for the dog.",broke:"Did not break. Chargers did."},
lac:{offscheme:"McDaniel wide zone and motion. First game as Chargers caller.",engine2:"Herbert still threw. Ladd was the tree. 14 points as a 9-point favorite.",offhole:"Could not finish. Lost outright.",howoff:"Do not stack leaking home chalk.",broke:"Red zone and explosives. They moved it some. They did not cash."},
gb:{offscheme:"LaFleur dropback. Early explosives.",engine2:"Love 387. Watson 147. They moved it in bunches before Flores ended it.",offhole:"Offensive line. Time to pressure under 2.50. Lead died 22-10.",howoff:"Love yards are not the Packers side.",broke:"The line vs stacked pressure. Production was real. The side died."},
min:{offscheme:"O'Connell / Phillips. Jefferson plus a closer script.",engine2:"Jefferson 8-92-2. Mason 59 rush. Last 29 points.",offhole:"First three quarters. Trailed 22-10.",howoff:"Jefferson. Minnesota late.",broke:"Early. The closer script is the identity."},
mia:{offscheme:"Slowik dropback. Never found a second-half answer.",engine2:"They still completed passes. 13 points. No featured-back answer the other way.",offhole:"Never in the number after Q1.",howoff:"Do not stack Miami vs a featured home back.",broke:"After the first quarter. Jeanty cooked the plan."},
lv:{offscheme:"Kubiak / Janocko. Featured back is the call.",engine2:"Jeanty 23-102 and two receiving TDs. Willis 220.",offhole:"Did not break.",howoff:"Jeanty, then the home number.",broke:"Did not break."},
wsh:{offscheme:"Blough first-year call. Daniels live.",engine2:"Daniels kept drives alive. 22 points. Stayed inside a field goal.",offhole:"Could not finish the upset.",howoff:"The cover was the number, not a Washington stack.",broke:"Red zone. They moved it enough to cash +5.5."},
phi:{offscheme:"Mannion first-year call. Hurts. Barkley. Goedert in the red zone.",engine2:"Hurts 203. Barkley 83. Goedert 4-77-2.",offhole:"Could not pull away. Won by 2.",howoff:"Goedert in a tight script. Not the home number.",broke:"Everything except the goal line stayed inside a field goal."},
dal:{offscheme:"Schottenheimer / Adams. Brand dropback.",engine2:"They moved it some. Not enough to keep up with Dart. 20 points.",offhole:"Lost outright by 8.",howoff:"Brand is not a stack.",broke:"Could not match New York's explosives."},
nyg:{offscheme:"Nagy. Dart. Tight end in the red zone.",engine2:"Dart 230 and three TDs. Likely two TDs. Nabers 69. Skattebo 81. Dart 54 rush.",offhole:"Did not break. Defense had zero sacks so offense had to carry.",howoff:"Likely is the isolation.",broke:"Did not break."},
den:{offscheme:"LIVE. Webb first-year call.",engine2:"LIVE.",offhole:"LIVE.",howoff:"Wait for the final.",broke:"LIVE."},
kc:{offscheme:"LIVE. Bieniemy. Walker planned as the run focal point.",engine2:"LIVE.",offhole:"LIVE.",howoff:"Wait for the final.",broke:"LIVE."}
};
(function(){
  const I = window.NFL_IDENTITIES || {};
  Object.keys(window.NFL_OFF||{}).forEach(function(k){
    const d = window.NFL_OFF[k];
    if (!I[k]) return;
    I[k].offscheme = d.offscheme; I[k].engine2 = d.engine2; I[k].offhole = d.offhole; I[k].howoff = d.howoff; I[k].broke = d.broke;
  });
  if (I.was && window.NFL_OFF.wsh){
    ["offscheme","engine2","offhole","howoff","broke"].forEach(function(f){ I.was[f] = window.NFL_OFF.wsh[f]; });
  }
})();
