window.NFL_ID_A = {
ne:{name:"New England Patriots",w1:"SEA 13-10",ticket:"+3 PUSH",pf:10,pa:13,style:"LOW-TOTAL DOG",engine:"Maye (3 INT)",stat:"10 points",who:"Road dog in a total under 45. The number held. The pass game did not.",bet:"Points in a low total. Not the QB.",dfs:"Skip Maye. TE or a back if you need a Patriot.",next:"Dog under 45: start with the number, not Maye as captain.",rev:"nfl-week-1-ne-sea-review.html"},
sea:{name:"Seattle Seahawks",w1:"SEA 13-10",ticket:"-3 PUSH",pf:13,pa:10,style:"LOW-TOTAL HOME",engine:"JSN 8-122-1",stat:"13 points \u00b7 never pulled away",who:"Home favorite that won and only tied the number. JSN was the tree.",bet:"Winning is not covering. Do not smash this home number.",dfs:"JSN only. Do not force the rest of the room.",next:"Next Seattle home favorite: can they pull away? If not, the dog still has a number.",rev:"nfl-week-1-ne-sea-review.html"},
sf:{name:"San Francisco 49ers",w1:"SF 27-7",ticket:"+3.5 WIN",pf:27,pa:7,style:"ROAD DOG THAT RUNS",engine:"Purdy + the run game",stat:"Won by 20",who:"Road dog that can run. Short-week home favorite died.",bet:"Take the dog when the favorite is on a short week and SF can run.",dfs:"CMC 68 rush, 20 rec, zero TDs. Volume is not a captain.",next:"Short-week favorite vs SF: fade the home QB stack. Board the dog.",rev:"nfl-week-1-sf-lar-review.html"},
lar:{name:"Los Angeles Rams",w1:"SF 27-7",ticket:"-3.5 LOSS",pf:7,pa:27,style:"SHORT-WEEK CHALK",engine:"Home QB stack died",stat:"7 points",who:"Short-week home favorite. Lost the script by 20.",bet:"Fade the short-week home favorite when the dog can run.",dfs:"Do not stack the home QB in that spot.",next:"Next Rams short week: travel and rest first, not the brand.",rev:"nfl-week-1-sf-lar-review.html"},
chi:{name:"Chicago Bears",w1:"CHI 59-37",ticket:"-3 WIN",pf:59,pa:37,style:"EXPLOSIVE RUN",engine:"Swift 18-124-3 \u00b7 Monangai 100-1 \u00b7 Williams 2 pass TD + 2 rush TD",stat:"552 yards \u00b7 291 rush",who:"Better run team in the highest-scoring Week 1 game. Never let Carolina into the number.",bet:"When Chicago is the better run club, take the favorite and the back.",dfs:"Swift is the slate. Cap the other Bears.",next:"Bears favorite vs a soft run D: Chicago side and Swift, not a quiet total.",rev:"nfl-week-1-game-review.html#chi-car"},
car:{name:"Carolina Panthers",w1:"CHI 59-37",ticket:"+3 LOSS",pf:37,pa:59,style:"PASS VOLUME, NO RUN D",engine:"Young 361-3 \u00b7 Coker 8-138",stat:"Allowed 291 rush and 6 rush TDs",who:"Could throw. Could not stop the run.",bet:"Do not buy Carolina points vs a real run team.",dfs:"Coker is the ceiling. Do not build the side on Carolina.",next:"Carolina vs a run identity: fade the points. Write the rush D first.",rev:"nfl-week-1-game-review.html#chi-car"},
tb:{name:"Tampa Bay Buccaneers",w1:"CIN 33-27",ticket:"+3.5 LOSS",pf:27,pa:33,style:"BACK SCORES, SIDE DIES",engine:"Irving rush TD",stat:"Lost by 6",who:"Road dog vs Burrow at home. Number lost. Back cashed.",bet:"Do not treat +3.5 as free vs Burrow at home.",dfs:"Irving without the Bucs side.",next:"Bucs road dog: Irving can be live while +3.5 is not.",rev:"nfl-week-1-game-review.html#tb-cin"},
cin:{name:"Cincinnati Bengals",w1:"CIN 33-27",ticket:"-3.5 WIN",pf:33,pa:27,style:"HOME COVER, QUIET WR1",engine:"Burrow 254. Defense scored.",stat:"Covered. Chase quiet.",who:"Burrow at home covered. Chase did not go off.",bet:"Respect Burrow at home.",dfs:"Cap Chase. The front and the other skill won it.",next:"Bengals home: the side can be real if Chase is quiet.",rev:"nfl-week-1-game-review.html#tb-cin"},
no:{name:"New Orleans Saints",w1:"DET 31-30 OT",ticket:"+7.5 WIN",pf:30,pa:31,style:"PASS-CEILING DOG",engine:"Shough 410 \u00b7 Olave 182",stat:"Covered +7.5. Lost in OT.",who:"Covered a large home number. Lost the game in OT.",bet:"Take the points when Detroit is a big home favorite.",dfs:"Olave is the Saint. Gibbs is still the Lion.",next:"Saints dog vs a TD+ home favorite: points and Olave.",rev:"nfl-week-1-game-review.html#no-det"},
det:{name:"Detroit Lions",w1:"DET 31-30 OT",ticket:"-7.5 LOSS",pf:31,pa:30,style:"HOME CHALK THAT LEAKS",engine:"Gibbs 29-156-2",stat:"Won in OT. Did not cover 7.5.",who:"Home favorite that leaked. Gibbs was the engine.",bet:"Do not lay a big Week 1 home number on the name.",dfs:"Gibbs cashed. Cap him.",next:"Lions home favorite of a TD or more: start with the leak.",rev:"nfl-week-1-game-review.html#no-det"},
buf:{name:"Buffalo Bills",w1:"BUF 36-31",ticket:"-1.5 WIN",pf:36,pa:31,style:"CLOSER",engine:"Allen 334 pass + 2 rush TD",stat:"Kincaid 130 yards, 0 TD",who:"Better closer. Needed five and got them.",bet:"Take the favorite when Buffalo is the closer.",dfs:"Kincaid yards are not a captain.",next:"Bills road favorite: the side is Allen closing. Do not attach the TE TD.",rev:"nfl-week-1-game-review.html#buf-hou"},
hou:{name:"Houston Texans",w1:"BUF 36-31",ticket:"+1.5 LOSS",pf:31,pa:36,style:"ONE-SCORE HOME",engine:"Montgomery 3 TD",stat:"Kept it one score. Did not cover.",who:"Stayed close. Montgomery scored three.",bet:"Keeping it one score is not covering.",dfs:"Montgomery is the Texan.",next:"Texans small home dog: like Montgomery without needing the points.",rev:"nfl-week-1-game-review.html#buf-hou"},
bal:{name:"Baltimore Ravens",w1:"BAL 41-23",ticket:"-3 WIN",pf:41,pa:23,style:"RUN IDENTITY",engine:"Henry 24-144-3 \u00b7 Lamar 324 \u00b7 Flowers 150",stat:"Won by 18 on the road",who:"Run-game identity on the road.",bet:"When they run it, take the favorite and the back.",dfs:"Henry is the Raven.",next:"Ravens -3: Henry first, then Lamar.",rev:"nfl-week-1-game-review.html#bal-ind"},
ind:{name:"Indianapolis Colts",w1:"BAL 41-23",ticket:"+3 LOSS",pf:23,pa:41,style:"HOME THAT GOT RUN ON",engine:"Taylor 98-2",stat:"Allowed Henry 144-3",who:"Could not keep the Ravens run game inside the number.",bet:"Do not buy Colts points when Baltimore is running it.",dfs:"Taylor is the Colt. Do not stack the rest vs that script.",next:"Colts home vs a run identity: first line is their run D.",rev:"nfl-week-1-game-review.html#bal-ind"},
cle:{name:"Cleveland Browns",w1:"JAX 34-10",ticket:"+8.5 LOSS",pf:10,pa:34,style:"DEAD ROAD OFFENSE",engine:"None",stat:"Lost by 24",who:"Offense was not a Week 1 number.",bet:"A fat number still loses if the offense cannot move.",dfs:"Do not board this offense.",next:"Browns +7 or more: only fire if the offense can move.",rev:"nfl-week-1-game-review.html#cle-jax"},
jax:{name:"Jacksonville Jaguars",w1:"JAX 34-10",ticket:"-8.5 WIN",pf:34,pa:10,style:"HOME SMASH",engine:"Lawrence 245 \u00b7 4 TD passes",stat:"Covered a large home number",who:"Home smash against a dead road offense.",bet:"Lay it at home vs a dead road offense.",dfs:"Home DST plus one Jaguar skill.",next:"Jaguars large home number vs a bad offense: the breakdown can lay it.",rev:"nfl-week-1-game-review.html#cle-jax"}
};
