window.NFL_ID_B = {
atl:{name:"Atlanta Falcons",w1:"PIT 20-13",ticket:"+6.5 LOSS",pf:13,pa:20,style:"BIJAN, NOT AN OFFENSE",engine:"Bijan 83 rush + 90 rec + 1 TD",stat:"Lost by 7 · +6.5 misses by a half point",who:"The player cashed. The side did not.",bet:"A 7-point loss does not cash +6.5.",dfs:"Bijan is the Falcon.",next:"Next Falcons dog: isolate Bijan without needing +6.5.",rev:"nfl-week-1-game-review.html#atl-pit"},
pit:{name:"Pittsburgh Steelers",w1:"PIT 20-13",ticket:"-6.5 WIN",pf:20,pa:13,style:"UGLY HOME COVER",engine:"Rodgers 221 · defense + Watt",stat:"20-13 · defense traveled farther than the offense",who:"Ugly home cover. Did not need 30 points.",bet:"Take Pittsburgh at home in an ugly script.",dfs:"Do not pay the Steelers pass game in a 20-13.",next:"Next Steelers home under 44: the number and the defense, not the passing stack.",rev:"nfl-week-1-game-review.html#atl-pit"},
nyj:{name:"New York Jets",w1:"NYJ 23-10",ticket:"+1.5 WIN",pf:23,pa:10,style:"ROAD RUN DOG",engine:"Hall 22-102-1 · Geno 215",stat:"Beat a home opener by 13",who:"Best player on the field was Hall.",bet:"A home opener is not a cover by itself.",dfs:"Hall is the Jet.",next:"Next Jets dog with Hall healthy: start with Hall and the points.",rev:"nfl-week-1-game-review.html#nyj-ten"},
ten:{name:"Tennessee Titans",w1:"NYJ 23-10",ticket:"-1.5 LOSS",pf:10,pa:23,style:"DEAD HOME OPENER",engine:"Home opener script died",stat:"10 points at home",who:"Home opener did not hold.",bet:"Do not lay Titans home juice just because it is week one.",dfs:"Do not stack the leaking home opener.",next:"Next Titans home favorite: first question is whether the offense exists.",rev:"nfl-week-1-game-review.html#nyj-ten"},
ari:{name:"Arizona Cardinals",w1:"ARI 26-14",ticket:"+9.5 WIN",pf:26,pa:14,style:"ROAD UPSET DOG",engine:"Brissett 277 · McBride 95",stat:"Won outright as a 9-point dog",who:"Largest Week 1 upset. Harrison did not score.",bet:"Take the points when Chargers home chalk is that loud.",dfs:"Do not chain WR1 TD to a dog side you already like.",next:"Next Cardinals large dog: like the points without needing Harrison.",rev:"nfl-week-1-game-review.html#ari-lac"},
lac:{name:"Los Angeles Chargers",w1:"ARI 26-14",ticket:"-9.5 LOSS",pf:14,pa:26,style:"HOME CHALK THAT DIED",engine:"Home stack leaked",stat:"Lost outright as a 9-point favorite",who:"Week 1 home chalk died.",bet:"Fade large Chargers home numbers until the tape changes.",dfs:"Do not default the whole stack to leaking home chalk.",next:"Next Chargers home favorite of a TD or more: start with the leak.",rev:"nfl-week-1-game-review.html#ari-lac"},
gb:{name:"Green Bay Packers",w1:"MIN 39-22",ticket:"+1.5 LOSS",pf:22,pa:39,style:"VOLUME WITHOUT COVER",engine:"Love 387 · Watson 147",stat:"387 pass yards · lost by 17",who:"Yards piled. The side died.",bet:"Do not buy a pick-em dog just because the QB can pile yards.",dfs:"Love volume is not the side.",next:"Next Packers pick-em: separate Love yards from the number.",rev:"nfl-week-1-game-review.html#gb-min"},
min:{name:"Minnesota Vikings",w1:"MIN 39-22",ticket:"-1.5 WIN",pf:39,pa:22,style:"HOME CLOSER",engine:"Jefferson 8-92-2 · last 29 points",stat:"Won by 17 after trailing",who:"Scored the last 29. Jefferson was the ceiling.",bet:"Respect Minnesota at home when they start running after you.",dfs:"Jefferson is the Viking.",next:"Next Vikings home: Jefferson first. The closer script is the side.",rev:"nfl-week-1-game-review.html#gb-min"},
mia:{name:"Miami Dolphins",w1:"LV 27-13",ticket:"+3.5 LOSS",pf:13,pa:27,style:"ROAD DOG THAT NEVER ENTERED",engine:"Never in the number after Q1",stat:"13 points · lost by 14",who:"Never entered the number after the first quarter.",bet:"Do not buy Miami points against a featured home back.",dfs:"Do not stack Miami in that script.",next:"Next Dolphins road dog vs a real home back: fade the points until Miami shows a half.",rev:"nfl-week-1-game-review.html#mia-lv"},
lv:{name:"Las Vegas Raiders",w1:"LV 27-13",ticket:"-3.5 WIN",pf:27,pa:13,style:"FEATURED-BACK HOME",engine:"Jeanty 23-102 + two rec TDs",stat:"Two Jeanty receiving TDs",who:"New-look home club. Jeanty is the identity.",bet:"Respect the home number when Jeanty is the identity.",dfs:"Jeanty is the Raider.",next:"Next Raiders home: Jeanty, then the number. Not the cheap TE.",rev:"nfl-week-1-game-review.html#mia-lv"},
wsh:{name:"Washington Commanders",w1:"PHI 24-22",ticket:"+5.5 WIN",pf:22,pa:24,style:"RIVALRY DOG",engine:"Daniels live · stayed inside FG",stat:"Lost by 2 · +5.5 cashed",who:"Rivalry-week road dog. The number was the ticket.",bet:"Take the points when Philadelphia is home chalk.",dfs:"The cover was the number, not the Washington stack.",next:"Next Commanders +5 vs a brand home favorite: board the points first.",rev:"nfl-week-1-wsh-phi-review.html"},
phi:{name:"Philadelphia Eagles",w1:"PHI 24-22",ticket:"-5.5 LOSS",pf:24,pa:22,style:"HOME CHALK THAT LEAKS",engine:"Hurts 203 · Barkley 83 · Goedert 4-77-2",stat:"Won by 2 · did not cover 5.5",who:"Won the opener. Did not cover. Goedert lives on the goal line.",bet:"Home chalk in a rivalry week leaks. Do not lay 5.5.",dfs:"Goedert is the Eagle in a tight script.",next:"Next Eagles home favorite of a TD: fade the number and still play Goedert.",rev:"nfl-week-1-wsh-phi-review.html"},
dal:{name:"Dallas Cowboys",w1:"NYG 28-20",ticket:"-2.5 LOSS",pf:20,pa:28,style:"BRAND ROAD FAVORITE",engine:"Brand was the number",stat:"Lost outright by 8",who:"Road favorite on Sunday night because of the name.",bet:"Do not assume the bigger brand covers in Week 1.",dfs:"Brand is not a stack.",next:"Next Cowboys road favorite of a field goal: ask if they are good or just famous.",rev:"nfl-week-1-game-review.html#dal-nyg"},
nyg:{name:"New York Giants",w1:"NYG 28-20",ticket:"+2.5 WIN",pf:28,pa:20,style:"HOME DOG THAT WINS",engine:"Dart 230 · Skattebo 81 · Likely TD",stat:"Beat the brand outright",who:"Beat Dallas at home. Likely scored.",bet:"Take Giants points against a favorite that is only a favorite because of the name.",dfs:"Likely was the isolation.",next:"Next Giants home vs a brand favorite: board the points and one Giant skill.",rev:"nfl-week-1-game-review.html#dal-nyg"},
den:{name:"Denver Broncos",w1:"KC 31-10",ticket:"+2.5 LOSS",pf:10,pa:31,style:"DEAD ROAD DOG",engine:"Nix 131 · Engram 19-yd TD",stat:"176 yards · 9 first downs · 61 rush",who:"Road dog that never moved it. +2.5 died by three scores.",bet:"Do not buy Denver points when the other club has a featured home back.",dfs:"Do not stack Nix. Engram scored. That was the tree.",next:"Next Broncos dog: only fire if the offense can stay on the field.",rev:"nfl-week-1-den-kc-review.html"},
kc:{name:"Kansas City Chiefs",w1:"KC 31-10",ticket:"-2.5 WIN",pf:31,pa:10,style:"FEATURED-BACK HOME",engine:"Walker 173 rush + 2 TD",stat:"392 yards · 220 rush · 19 first downs",who:"Mahomes return was real. Walker was the game.",bet:"Respect the short home number when Walker is the script.",dfs:"Walker is the Chief. Worthy is not the captain.",next:"Next Chiefs home: Walker first. Do not fade this club with a dog ticket.",rev:"nfl-week-1-den-kc-review.html"}
};
