window.NFL_ID_A = {
ne:{name:"New England Patriots",w1:"SEA 13-10",ticket:"+3 PUSH",pf:10,pa:13,style:"LOW-TOTAL DOG",engine:"Maye (3 INT)",stat:"10 points \u00b7 passing script died",who:"Road dog in a total under 45. Cover number hit. The pass game did not.",bet:"Take the points in a low total. Do not captain the QB.",dfs:"TE and backs first. Henry did not score.",next:"If New England is a dog under 45 again, the breakdown starts with the number, not Maye as captain.",rev:"nfl-week-1-ne-sea-review.html"},
sea:{name:"Seattle Seahawks",w1:"SEA 13-10",ticket:"-3 PUSH",pf:13,pa:10,style:"LOW-TOTAL HOME",engine:"JSN 8-122-1",stat:"13 points \u00b7 never pulled away",who:"Home favorite that won and still only tied the number. JSN was the tree.",bet:"Do not smash a short-week home favorite just because they won.",dfs:"JSN is the Seahawk. Do not force the rest of the room.",next:"Next Seattle home favorite: ask if they can pull away. If not, the dog still has a number.",rev:"nfl-week-1-ne-sea-review.html"},
sf:{name:"San Francisco 49ers",w1:"SF 27-7",ticket:"+3.5 WIN",pf:27,pa:7,style:"ROAD DOG THAT RUNS",engine:"Purdy + run game",stat:"Won by 20 on a short-week favorite",who:"Road dog that can run. Travel-week favorite died.",bet:"Take the dog when the favorite is on a short week and SF can run.",dfs:"CMC 68 rush, 20 rec, zero TDs. Volume is not a captain.",next:"Next short-week favorite vs SF: fade the home QB stack. Board the dog.",rev:"nfl-week-1-sf-lar-review.html"},
lar:{name:"Los Angeles Rams",w1:"SF 27-7",ticket:"-3.5 LOSS",pf:7,pa:27,style:"SHORT-WEEK CHALK",engine:"Stafford home stack died",stat:"7 points after the first half",who:"Short-week home favorite. Lost the script by 20 in Melbourne.",bet:"Fade the short-week home favorite when the dog can run.",dfs:"Do not stack the home QB in that spot.",next:"Next Rams short week: the breakdown starts with travel and rest, not the brand.",rev:"nfl-week-1-sf-lar-review.html"},
chi:{name:"Chicago Bears",w1:"CHI 59-37",ticket:"-3 WIN",pf:59,pa:37,style:"EXPLOSIVE RUN",engine:"Swift 18-124-3 \u00b7 Monangai 100-1 \u00b7 Williams 269/2 pass + 65 rush",stat:"552 yards \u00b7 6 rush TDs allowed by CAR",who:"Better run team in the highest-scoring Week 1 game ever. Never let Carolina into the number.",bet:"When Chicago is the better run club, take the favorite and the back.",dfs:"Swift is the slate. Five Bears scored. Cap the chalk, still play the back.",next:"Next Bears favorite: if the other run D is soft, the breakdown is Chicago -3 and Swift, not a quiet total.",rev:"nfl-week-1-game-review.html#chi-car"},
car:{name:"Carolina Panthers",w1:"CHI 59-37",ticket:"+3 LOSS",pf:37,pa:59,style:"PASS VOLUME, NO RUN D",engine:"Young 23-37-361-3 \u00b7 Coker 8-138",stat:"Allowed 291 rush yards and 6 rush TDs",who:"Could throw. Could not stop the run. 96-point game.",bet:"Do not buy Carolina points when a real run team can run.",dfs:"Coker ceiling is real. Do not build the side on Carolina.",next:"Next Carolina home vs a run identity: fade the points. Note the rush D first.",rev:"nfl-week-1-game-review.html#chi-car"},
tb:{name:"Tampa Bay Buccaneers",w1:"CIN 33-27",ticket:"+3.5 LOSS",pf:27,pa:33,style:"ROAD DOG, BACK STILL SCORES",engine:"Irving 8-45-1",stat:"Lost by 6 \u00b7 Irving still found the end zone",who:"Road dog against Burrow at home. The number lost. The back cashed.",bet:"Road dog in Week 1 against Burrow is not free.",dfs:"Separate Irving from the side.",next:"Next Bucs road dog: the breakdown can like Irving without liking +3.5.",rev:"nfl-week-1-game-review.html#tb-cin"},
cin:{name:"Cincinnati Bengals",w1:"CIN 33-27",ticket:"-3.5 WIN",pf:33,pa:27,style:"HOME BURROW",engine:"Burrow 254 \u00b7 Brown 56 \u00b7 Gesicki 78",stat:"Covered at home \u00b7 Chase was quiet",who:"Burrow at home covered. Chase did not go off.",bet:"Respect Burrow at home.",dfs:"Field stacks Chase. Cap him. The other back still scored.",next:"Next Bengals home: the side can be real even if Chase is quiet.",rev:"nfl-week-1-game-review.html#tb-cin"},
no:{name:"New Orleans Saints",w1:"DET 31-30 OT",ticket:"+7.5 WIN",pf:30,pa:31,style:"PASS CEILING DOG",engine:"Shough 410 \u00b7 Olave 182",stat:"410 pass yards \u00b7 covered +7.5 by a mile",who:"Covered a large home number. Lost in OT.",bet:"Take the points when Detroit is a big home favorite.",dfs:"Olave ceiling is real. Gibbs is still the Lion.",next:"Next Saints dog vs a big home favorite: board the points and Olave.",rev:"nfl-week-1-game-review.html#no-det"},
det:{name:"Detroit Lions",w1:"DET 31-30 OT",ticket:"-7.5 LOSS",pf:31,pa:30,style:"HOME CHALK THAT LEAKS",engine:"Gibbs 29-156-2 \u00b7 St. Brown 2 TD",stat:"Won in OT \u00b7 did not cover 7.5",who:"Home favorite that leaked. Gibbs was the engine.",bet:"Do not lay a big home number in Week 1 just because of the name.",dfs:"Gibbs is chalk and he cashed. Cap him at 8 of 50.",next:"Next Lions home favorite of a TD or more: start with the leak.",rev:"nfl-week-1-game-review.html#no-det"},
buf:{name:"Buffalo Bills",w1:"BUF 36-31",ticket:"-1.5 WIN",pf:36,pa:31,style:"CLOSER",engine:"Allen 334 pass + 2 rush TD",stat:"67 points \u00b7 Kincaid 130, 0 TD",who:"Better closer. Needed five and got them.",bet:"Take the favorite when Buffalo is the closer.",dfs:"Kincaid yards are not a captain.",next:"Next Bills road favorite: the side is Allen closing. Do not attach the TE TD.",rev:"nfl-week-1-game-review.html#buf-hou"},
hou:{name:"Houston Texans",w1:"BUF 36-31",ticket:"+1.5 LOSS",pf:31,pa:36,style:"ONE-SCORE HOME",engine:"Montgomery 2 rush TD + 1 rec TD",stat:"Kept it one score \u00b7 did not cover",who:"Stayed close. Montgomery scored three.",bet:"Houston can keep it one score. That is not covering.",dfs:"Montgomery was the Houston engine.",next:"Next Texans home small dog: like Montgomery without needing the points.",rev:"nfl-week-1-game-review.html#buf-hou"},
bal:{name:"Baltimore Ravens",w1:"BAL 41-23",ticket:"-3 WIN",pf:41,pa:23,style:"RUN IDENTITY",engine:"Henry 24-144-3 \u00b7 Lamar 324 \u00b7 Flowers 150",stat:"Won by 18 on the road",who:"Run-game identity showed up on the road.",bet:"When the run game is the identity, take the favorite and the back.",dfs:"Henry is the slate.",next:"Next Ravens -3: Henry first, then Lamar.",rev:"nfl-week-1-game-review.html#bal-ind"},
ind:{name:"Indianapolis Colts",w1:"BAL 41-23",ticket:"+3 LOSS",pf:23,pa:41,style:"HOME THAT GOT RUN ON",engine:"Could not stop Henry",stat:"Allowed 144 and 3 to Henry",who:"Could not keep the Ravens run game inside the number.",bet:"Do not buy Colts points when Baltimore is running it.",dfs:"Do not stack Indy against that script.",next:"Next Colts home vs a run identity: first line is their run D.",rev:"nfl-week-1-game-review.html#bal-ind"},
cle:{name:"Cleveland Browns",w1:"JAX 34-10",ticket:"+8.5 LOSS",pf:10,pa:34,style:"DEAD ROAD OFFENSE",engine:"Hunter 0 TD",stat:"Lost by 24 \u00b7 +8.5 was not fat enough",who:"Offense was not a Week 1 number.",bet:"Fat road dogs still lose if the offense cannot move.",dfs:"Hunter did not score.",next:"Next Browns +7 or more: only fire if the offense can move.",rev:"nfl-week-1-game-review.html#cle-jax"},
jax:{name:"Jacksonville Jaguars",w1:"JAX 34-10",ticket:"-8.5 WIN",pf:34,pa:10,style:"HOME SMASH",engine:"Lawrence 245 \u00b7 4 TD passes",stat:"Covered a large home number easily",who:"Home smash against a dead road offense.",bet:"Respect Jacksonville at home against a dead road offense.",dfs:"Home DST plus one Jaguar skill.",next:"Next Jaguars large home number vs a bad offense: the breakdown can lay it.",rev:"nfl-week-1-game-review.html#cle-jax"}
};
