Object.assign(window.W1, {
"no-det":{away:"no",home:"det",awayName:"New Orleans Saints",homeName:"Detroit Lions",when:"Sunday, Sept. 13, 2026 | 1:00 p.m. ET | Ford Field | FOX",spread:"DET -7 (-108) / NO +7 (-112)",total:"49.5",ml:"DET -310 / NO +250",move:"Home favorite a touchdown",
awayNote:"Road dog | implied ~21",homeNote:"Home favorite | implied ~28",
awayStaff:[["HC Kellen Moore or the 2026 Saints chair","New script. Young / Carr-era is gone -- confirm starter Saturday."],["OC","11 personnel."],["DC","Has to tackle Gibbs in space."]],
homeStaff:[["HC Dan Campbell","Physical identity."],["OC Drew Petzing (calls plays - offense)","Replaces Ben Johnson. First Lions opener as the caller."],["DC Kelvin Sheppard (calls plays - defense)","Year 2. Wants the Saints in obvious passing downs."]],
awayMean:["+7 is the number we fade until Detroit proves the gap without Johnson calling it."],
homeMean:["Petzing's first script. Gibbs / Montgomery still the identity."],
awayKeys:["Saints QB of record","Alvin Kamara if active","Chris Olave"],
homeKeys:["Jared Goff","Jahmyr Gibbs","Amon-Ra St. Brown","David Montgomery"],
awayNews:["Confirm Saints QB and Kamara status Saturday."],homeNews:["Petzing Year 1 as the caller."],
cover:["Amon-Ra vs Saints CB1. Olave vs the Lions boundary."],
homeScore:"DET 30 | NO 20",homeIf:["Gibbs hits the edge.","Petzing's first script looks like last year."],
awayScore:"NO 24 | DET 23",awayIf:["Detroit stalls in the red zone.","Olave wins one-on-one."],
dfs:["Amon-Ra is the lock WR. Gibbs over Montgomery in cash.","Saints: Olave leverage. Kamara if volume."],
bet:"SAINTS +7 (-112)",stake:"$100 to win $89",why:["Week 1 home chalk of a touchdown.","New Lions caller. Let Detroit beat 7, not 3."]},
"buf-hou":{away:"buf",home:"hou",awayName:"Buffalo Bills",homeName:"Houston Texans",when:"Sunday, Sept. 13, 2026 | 1:00 p.m. ET | NRG Stadium | CBS",spread:"BUF -1.5 (-108) / HOU +1.5 (-112)",total:"44.5",ml:"BUF -122 / HOU +102",move:"Pick-em band",
awayNote:"Road favorite | implied ~23",homeNote:"Home dog | implied ~21",
awayStaff:[["HC Joe Brady (calls plays - offense)","Year 1 as HC. Was the Bills OC."],["OC Pete Carmichael Jr.","Does not take the headset if Brady keeps it."],["DC Jim Leonhard (calls plays - defense)","New. Two-high with pressure."]]
,homeStaff:[["HC DeMeco Ryans","Physical identity."],["OC Nick Caley (calls plays - offense)","Play-action, 12 personnel to protect Stroud."],["DC Matt Burke (calls plays - defense)","Wants Allen in obvious passing downs."]],
awayMean:["Brady's first opener as HC on the road. Allen is still the best player on the field."],
homeMean:["Stroud at home in a 44.5. If the Texans win early downs, +1.5 is live."],
awayKeys:["Josh Allen","James Cook","Khalil Shakir / Keon Coleman"],
homeKeys:["C.J. Stroud","Nico Collins","Joe Mixon or the 2026 lead back"],
awayNews:["Brady Year 1 HC."],homeNews:["Confirm Houston RB room Saturday."],
cover:["Collins vs Tre'Davious if active. Shakir vs the Texans nickel."],
homeScore:"HOU 23 | BUF 21",homeIf:["Stroud is clean.","Houston wins first down."],
awayScore:"BUF 24 | HOU 17",awayIf:["Allen extends drives.","Cook wins early downs."],
dfs:["Allen is the cash QB on a short number. Cook if BUF leans run.","Houston: Collins is the WR1. Stroud only in GPPs."],
bet:"BILLS -1.5 (-108)",stake:"$108 to win $100",why:["Allen on a number this short.","Brady has called this offense. Houston has to prove the home-dog path."]},
"bal-ind":{away:"bal",home:"ind",awayName:"Baltimore Ravens",homeName:"Indianapolis Colts",when:"Sunday, Sept. 13, 2026 | 1:00 p.m. ET | Lucas Oil Stadium | CBS",spread:"BAL -3.5 (-105) / IND +3.5 (-115)",total:"47.5",ml:"BAL -175 / IND +145",move:"Jones Achilles return",
awayNote:"Road favorite | implied ~25",homeNote:"Home dog | implied ~22",
awayStaff:[["HC Jesse Minter","New chair."],["OC Declan Doyle (calls plays - offense)","New. Lamar still the engine."],["DC Anthony Weaver (calls plays - defense)","New. Wants Jones off the spot."]],
homeStaff:[["HC Shane Steichen","Taylor is the plan."],["OC Jim Bob Cooter","Jones coming off Achilles. Reduced scramble volume."],["DC Lou Anarumo (calls plays - defense)","Knows Lamar from the Burrow years."]],
awayMean:["New HC/OC/DC on the road. The talent is still Lamar and Henry."],
homeMean:["Jones first game back. Taylor anytime is the market's favorite prop."],
awayKeys:["Lamar Jackson","Derrick Henry","Zay Flowers"],
homeKeys:["Daniel Jones","Jonathan Taylor","Josh Downs / Alec Pierce"],
awayNews:["Minter Year 1."],homeNews:["Jones Achilles. Expect a managed first half."],
cover:["Flowers vs Colts CB1. Downs vs the Ravens nickel."],
homeScore:"IND 24 | BAL 23",homeIf:["Taylor wins early downs.","Anarumo keeps Lamar in the pocket."],
awayScore:"BAL 27 | IND 20",awayIf:["Lamar is himself.","Henry finishes two drives."],
dfs:["Taylor is the 1pm RB1. Flowers if Lamar is clean.","Jones is not a tournament captain on an Achilles."],
bet:"COLTS +3.5 (-115)",stake:"$100 to win $87",why:["Home dog getting more than a field goal.","Baltimore staff is new. Jones only has to manage, not scramble 12 times."]},
"cle-jax":{away:"cle",home:"jax",awayName:"Cleveland Browns",homeName:"Jacksonville Jaguars",when:"Sunday, Sept. 13, 2026 | 1:00 p.m. ET | EverBank Stadium | CBS",spread:"JAX -8.5 (-110) / CLE +8.5 (-110)",total:"39.5",ml:"JAX -470 / CLE +360",move:"CLE from +7.5 to +8.5. Watson start.",
awayNote:"Road dog | implied ~15",homeNote:"Home favorite | implied ~24",
awayStaff:[["HC Todd Monken","New. Pass-game identity with a short roster."],["OC Travis Switzer","New."],["DC Mike Rutenberg (calls plays - defense)","New. Has to stop Etienne."]]
,homeStaff:[["HC Liam Coen (calls plays - offense)","Year 2. 11 personnel."],["OC Grant Udinski","Coen still the voice."],["DC Anthony Campanile (calls plays - defense)","Wants Watson in obvious passing downs."]],
awayMean:["Watson start moved the number. 39.5 is a field-position game."],
homeMean:["Home favorite of a TD-plus. Lawrence has to finish."],
awayKeys:["Deshaun Watson","Quinshon Judkins / the CLE back","Jerry Jeudy"],
homeKeys:["Trevor Lawrence","Travis Etienne","Brian Thomas Jr."],
awayNews:["Watson start is why +8.5 exists."],homeNews:["Coen Year 2 opener at home."],
cover:["BTJ vs Browns CB1. Jeudy vs Jags boundary."],
homeScore:"JAX 24 | CLE 13",homeIf:["Etienne wins first down.","Lawrence avoids the negative play."],
awayScore:"CLE 17 | JAX 16",awayIf:["The total is the game.","Cleveland steals a short field."],
dfs:["Etienne / BTJ. Jags DST and kicker in a 39.5.","Do not captain Watson."],
bet:"BROWNS +8.5 (-110)",stake:"$110 to win $100",why:["Double-digit adjacent number in a 39.5.","Lose by 6 and cash."]},
"atl-pit":{away:"atl",home:"pit",awayName:"Atlanta Falcons",homeName:"Pittsburgh Steelers",when:"Sunday, Sept. 13, 2026 | 1:00 p.m. ET | Acrisure Stadium | FOX",spread:"PIT -3.5 / ATL +3.5",total:"41.5",ml:"PIT -185 / ATL +155",move:"Low total",
awayNote:"Road dog | implied ~19",homeNote:"Home favorite | implied ~22",
awayStaff:[["HC Kevin Stefanski","New in Atlanta."],["OC Tommy Rees (calls plays - offense)","New. Bijan is the plan."],["DC Jeff Ulbrich (calls plays - defense)","Wants the Steelers in obvious passing downs."]],
homeStaff:[["HC Mike Tomlin","Physical identity."],["OC Brian Angelichio","New."],["DC Patrick Graham (calls plays - defense)","New. Two-gap, late rotation."]],
awayMean:["Bijan is the slate RB in a 41.5."],homeMean:["Low total. Kicker and the run game matter more than the WR2."],
awayKeys:["Bijan Robinson","Drake London","Falcons QB of record"],
homeKeys:["Steelers QB of record","The PIT lead back","George Pickens is in Dallas -- confirm PIT WR1 Saturday."],
awayNews:["Stefanski Year 1 in Atlanta."],homeNews:["Graham Year 1. Pickens is a Cowboy now."],
cover:["London vs Steelers CB1."],
homeScore:"PIT 20 | ATL 17",homeIf:["Pittsburgh wins first down.","The kicker hits two."],
awayScore:"ATL 21 | PIT 17",awayIf:["Bijan gets 22 touches.","London wins one-on-one."],
dfs:["Bijan is the build. London if ATL throws.","Steelers: RB / K / DST before a WR2."],
bet:"FALCONS +3.5 (-108)",stake:"$100 to win $93",why:["Road dog getting more than a field goal in a 41.5.","New staffs on both sides. Take the points."]},
"nyj-ten":{away:"nyj",home:"ten",awayName:"New York Jets",homeName:"Tennessee Titans",when:"Sunday, Sept. 13, 2026 | 1:00 p.m. ET | Nissan Stadium | CBS",spread:"TEN -1.5 / NYJ +1.5",total:"38.5",ml:"TEN -125 / NYJ +105",move:"Lowest total on the board",
awayNote:"Road dog | implied ~18",homeNote:"Home favorite | implied ~20",
awayStaff:[["HC","Jets 2026 chair."],["OC Frank Reich","New. Geno / Breece is the plan."],["DC Brian Duker (calls plays - defense)","New."]],
homeStaff:[["HC","Titans 2026 chair."],["OC Brian Daboll (calls plays - offense)","New. Wants a clean first down."],["DC Gus Bradley (calls plays - defense)","Cover 3. Breece is the test."]],
awayMean:["38.5. Kickers and DST first."],homeMean:["Home favorite of a field goal in the lowest total of the week."],
awayKeys:["Geno Smith","Breece Hall","Garrett Wilson"],
homeKeys:["Titans QB of record","The TEN lead back","Calvin Ridley if still there -- confirm Saturday."],
awayNews:["Reich Year 1."],homeNews:["Daboll Year 1 as the Titans caller."],
cover:["Wilson vs Titans CB1."],
homeScore:"TEN 17 | NYJ 16",homeIf:["Tennessee wins first down.","The kicker hits two."],
awayScore:"NYJ 20 | TEN 13",awayIf:["Breece gets 20 touches.","Wilson wins one-on-one."],
dfs:["Breece is the only offensive cash piece. Both kickers are live.","Avoid both QBs as the build."],
bet:"TITANS -1.5 (-110)",stake:"$110 to win $100",why:["Home favorite in a 38.5.","Jets have to prove Reich's first script on the road."]},
"ari-lac":{away:"ari",home:"lac",awayName:"Arizona Cardinals",homeName:"Los Angeles Chargers",when:"Sunday, Sept. 13, 2026 | 4:25 p.m. ET | SoFi Stadium | CBS",spread:"LAC -9.5 / ARI +9.5",total:"47.5",ml:"LAC -500 / ARI +380",move:"Biggest spread of the week",
awayNote:"Road dog | implied ~19",homeNote:"Home favorite | implied ~28",
awayStaff:[["HC Mike LaFleur","New. Shanahan cousin tree."],["OC Nathaniel Hackett","New."],["DC Nick Rallis (calls plays - defense)","Has to tackle Ladd and the Chargers back."]]
,homeStaff:[["HC Jim Harbaugh","Physical identity."],["OC Mike McDaniel (calls plays - offense)","New. Motion, 11 personnel."],["DC Chris O'Leary (calls plays - defense)","First-time NFL DC."]],
awayMean:["+9.5 is the number we make Los Angeles beat. Love ankle is the Cardinals watch."],
homeMean:["McDaniel's first Chargers script. Herbert should be clean."],
awayKeys:["Cardinals QB of record","Marvin Harrison Jr.","Trey McBride","Jeremiyah Love -- ankle"],
homeKeys:["Justin Herbert","Ladd McConkey","The Chargers lead back"],
awayNews:["Love limited. Saturday designation."],homeNews:["McDaniel Year 1 in LA. O'Leary first-time DC."],
cover:["MHJ vs Chargers CB1. Ladd vs Cards nickel."],
homeScore:"LAC 30 | ARI 17",homeIf:["Herbert is clean.","McDaniel's motion holds."],
awayScore:"ARI 24 | LAC 23",awayIf:["Harrison wins two 50-50s.","Love is full-go and the Cards keep it on the ground."],
dfs:["Herbert / Ladd if you want the favorite. McBride is the Cardinals TE."],
bet:"CARDINALS +9.5 (-105)",stake:"$105 to win $100",why:["Laying double digits in Week 1.","New Chargers DC. Let them beat 10, not 3."]},
"mia-lv":{away:"mia",home:"lv",awayName:"Miami Dolphins",homeName:"Las Vegas Raiders",when:"Sunday, Sept. 13, 2026 | 4:25 p.m. ET | Allegiant Stadium | FOX",spread:"LV -3.5 / MIA +3.5",total:"40.5",ml:"LV -185 / MIA +155",move:"Bowers OUT",
awayNote:"Road dog | implied ~18",homeNote:"Home favorite | implied ~22",
awayStaff:[["HC","Dolphins 2026 chair."],["OC Bobby Slowik (calls plays - offense)","New. Achane is the engine."],["DC Sean Duggan (calls plays - defense)","New."]],
homeStaff:[["HC Klint Kubiak","New."],["OC Andrew Janocko","Kubiak likely keeps a hand on it."],["DC Rob Leonard (calls plays - defense)","New. Achane in space is the test."]],
awayMean:["40.5. Achane or nothing if Willis is the QB. Confirm starter Saturday."],
homeMean:["Bowers out. Mayer is the TE1. Jeanty ankle -- no designation."],
awayKeys:["Malik Willis or the Dolphins QB","De'Von Achane","Malik Washington"],
homeKeys:["Raiders QB of record","Ashton Jeanty","Michael Mayer -- Bowers out"],
awayNews:["Confirm Miami QB. Depth chart listed Willis."],homeNews:["Bowers meniscus trim. Out a game or two. Jeanty practicing."],
cover:["Mayer vs Dolphins LB/S. Achane vs Raiders nickel."],
homeScore:"LV 23 | MIA 16",homeIf:["Jeanty is full-go.","Mayer replaces enough of Bowers."],
awayScore:"MIA 20 | LV 17",awayIf:["Achane gets 18 touches.","Miami steals a short field."],
dfs:["Mayer is the non-star TE. Jeanty if the ankle is clean.","Achane is the Dolphins build."],
bet:"RAIDERS -3.5 (-118)",stake:"$118 to win $100",why:["Home favorite. Bowers miss is already in the number.","Miami on the road in Week 1 with QB questions."]},
"gb-min":{away:"gb",home:"min",awayName:"Green Bay Packers",homeName:"Minnesota Vikings",when:"Sunday, Sept. 13, 2026 | 4:25 p.m. ET | U.S. Bank Stadium | CBS",spread:"MIN -1.5 / GB +1.5",total:"46.5",ml:"MIN -122 / GB +102",move:"Opened GB -1.5. Flipped to MIN -1.5.",
awayNote:"Road dog | implied ~22",homeNote:"Home favorite | implied ~24",
awayStaff:[["HC Matt LaFleur (calls plays - offense)","11 personnel. Love's second read."],["OC Adam Stenavich","LaFleur still the voice."],["DC Jonathan Gannon (calls plays - defense)","New. Cardinals HC last year. Jefferson is the test."]],
homeStaff:[["HC Kevin O'Connell","McCarthy Year 2."],["OC Wes Phillips","O'Connell still the voice."],["DC Brian Flores (calls plays - defense)","Sim and pressure. Wants Love off the spot."]],
awayMean:["The flip off GB -1.5 is the tell."],homeMean:["Flores at home against Love is why the number moved."],
awayKeys:["Jordan Love","Josh Jacobs","Romeo Doubs / Jayden Reed"],
homeKeys:["J.J. McCarthy","Justin Jefferson","Jordan Addison","Aaron Jones if still there -- confirm."],
awayNews:["Gannon Year 1 in Green Bay."],homeNews:["Number flipped. Dollars on Minnesota."],
cover:["Jefferson vs Packers CB1. Doubs vs Flores' boundary."],
homeScore:"MIN 24 | GB 20",homeIf:["Jefferson wins two.","Flores gets Love on the ground."],
awayScore:"GB 23 | MIN 21",awayIf:["Jacobs wins first down.","Love beats the sim."],
dfs:["Jefferson is the cash WR. Love vs McCarthy is the GPP fork.","Reed / Addison are the unique WRs."],
bet:"VIKINGS -1.5 (-108)",stake:"$108 to win $100",why:["Respect the move off Green Bay.","Flores at home is the side until Love proves the sim." ]},
"wsh-phi":{away:"wsh",home:"phi",awayName:"Washington Commanders",homeName:"Philadelphia Eagles",when:"Sunday, Sept. 13, 2026 | 4:25 p.m. ET | Lincoln Financial Field | FOX",spread:"PHI -5.5 / WAS +5.5",total:"44.5",ml:"PHI -230 / WAS +190",move:"Home favorite",
awayNote:"Road dog | implied ~19",homeNote:"Home favorite | implied ~25",
awayStaff:[["HC Dan Quinn","Physical identity."],["OC David Blough","New."],["DC Daronte Jones (calls plays - defense)","New. Saquon is the test."]],
homeStaff:[["HC Nick Sirianni","Saquon is the plan."],["OC Sean Mannion","New. Sirianni still close to it."],["DC Vic Fangio (calls plays - defense)","Two-high. Wants Washington in obvious passing downs."]],
awayMean:["+5.5 is a lot if Daniels is himself. Confirm Daniels status Saturday."],
homeMean:["Saquon is the RB1 of the window. Fangio at home."],
awayKeys:["Jayden Daniels","The WAS lead back","Terry McLaurin"],
homeKeys:["Jalen Hurts","Saquon Barkley","A.J. Brown -- monitor. DeVonta Smith"],
awayNews:["Jones Year 1 DC."],homeNews:["Brown status is the Eagles watch."],
cover:["A.J. Brown vs Commanders CB1. McLaurin vs Quinyon."],
homeScore:"PHI 27 | WAS 17",homeIf:["Saquon gets 22 touches.","Fangio keeps Daniels in the pocket."],
awayScore:"WAS 23 | PHI 20",awayIf:["Daniels extends drives.","McLaurin wins two."],
dfs:["Saquon is the lock RB. Brown if full-go.","Commanders: McLaurin leverage."],
bet:"EAGLES -5.5 (-105)",stake:"$105 to win $100",why:["Home favorite with Fangio and Saquon.","Washington has to prove the road script first."]},
"dal-nyg":{away:"dal",home:"nyg",awayName:"Dallas Cowboys",homeName:"New York Giants",when:"Sunday, Sept. 13, 2026 | 8:20 p.m. ET | MetLife Stadium | NBC",
spread:"DAL -3 / NYG +3",total:"48.5",ml:"DAL -162 / NYG +136",move:"SNF",
awayNote:"Road favorite | implied ~26",homeNote:"Home dog | implied ~23",
awayStaff:[["HC Brian Schottenheimer (calls plays - offense)","Year 2. 11 personnel."],["OC Klayton Adams","Schottenheimer still the voice."],["DC Christian Parker (calls plays - defense)","New. Eagles DB coach last year. Nabers is the test."]],
homeStaff:[["HC","Giants 2026 chair."],["OC Matt Nagy (calls plays - offense)","New. Was KC OC."],["DC Dennard Wilson (calls plays - defense)","New. Lamb / Pickens is the test."]],
awayMean:["Tyler Smith on IR. Pickens is new. Lamb is still the tree."],
homeMean:["Nabers practicing fully after ACL. Snap count possible."],
awayKeys:["Dak Prescott","CeeDee Lamb","George Pickens","Javonte Williams"],
homeKeys:["Jaxson Dart or the Giants QB","Malik Nabers","Cam Skattebo"],
awayNews:["Smith IR. Pickens debut in Dallas colors."],homeNews:["Nabers full practice. Not a lock for 100% snaps."],
cover:["Lamb vs Giants CB1. Nabers vs Dallas CB1. Pickens vs the other outside."],
homeScore:"NYG 24 | DAL 23",homeIf:["Nabers is closer to full than managed.","Skattebo wins early downs."],
awayScore:"DAL 28 | NYG 21",awayIf:["Dak is clean.","Lamb / Pickens both eat."],
lineup:"<p class='note'>SNF Showdown. Captain note, not a locked six-man yet.</p><ul><li>Captain: Dak if this is a shootout. Nabers if he is full-go and unique.</li><li>Lamb / Pickens are the chalk WRs. Skattebo is the Giants non-star RB.</li><li>Do not default-captain the most-owned QB just because it is SNF.</li></ul>",
bet:"GIANTS +3 (-115)",stake:"$100 to win $87",why:["Home dog getting a field goal in a 48.5.","Dallas OL already dinged. Nabers being limited is already in the number."]},
"den-kc":{away:"den",home:"kc",awayName:"Denver Broncos",homeName:"Kansas City Chiefs",when:"Monday, Sept. 14, 2026 | 8:15 p.m. ET | Arrowhead | ABC/ESPN",
spread:"KC -2.5 / DEN +2.5",total:"43.5",ml:"KC -150 / DEN +124",move:"Mahomes ACL return",
awayNote:"Road dog | implied ~20",homeNote:"Home favorite | implied ~23",
awayStaff:[["HC Sean Payton","Physical, 12 personnel when he wants it."],["OC Davis Webb","Payton still close to the headset."],["DC Vance Joseph (calls plays - defense)","Wants Mahomes in the pocket. No scramble tax yet."]],
homeStaff:[["HC Andy Reid (calls plays - offense)","Mahomes first game back. Walker is the planned focal point."],["OC Eric Bieniemy","Back. Reid still the voice."],["DC Steve Spagnuolo (calls plays - defense)","Sim. Nix is the test."]],
awayMean:["+2.5 against a 9-month ACL is the same logic as Melbourne travel."],
homeMean:["Mahomes full participant. Rushing volume should be down. Walker is the build."],
awayKeys:["Bo Nix","Courtland Sutton","J.K. Dobbins"],
homeKeys:["Patrick Mahomes","Kenneth Walker III","Rashee Rice / Xavier Worthy"],
awayNews:["Mims full."],homeNews:["Mahomes FP. Rice / Worthy / Sneed expected."],
cover:["Sutton vs Chiefs CB1. Rice vs Broncos boundary. Worthy vs the nickel."],
homeScore:"KC 23 | DEN 17",homeIf:["Mahomes is clean and does not have to run.","Walker finishes two drives."],
awayScore:"DEN 21 | KC 20",awayIf:["Spags does not get home.","Nix answers the sim."],
lineup:"<p class='note'>MNF Showdown. Captain note, not a locked six-man yet.</p><ul><li>Captain: Walker over Mahomes if the thesis is a managed passing game.</li><li>Nix / Sutton if Denver stays in it. Bo as CPT only in a shootout that 43.5 does not want.</li><li>Kicker and DST are live in a 43.5.</li></ul>",
bet:"BRONCOS +2.5 (-102)",stake:"$100 to win $98",why:["Mahomes first game back.","Short home number. Medical version of the Melbourne number."]}
});
